/** @format */

import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Pages.module.css";

export default function Home() {
	const [blogs, setBlogs] = useState([]);
	blogs.length = 4;

	useEffect(() => {
		fetch("http://localhost:3000/api/getBlogs")
			.then((e) => {
				return e.json();
			})
			.then((e) => {
				setBlogs(e);
			});
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className="text-6xl justify-center mx-10 mt-10 font-barlow">
					Welcome to
					<Link href="/">
						<code className="text-cyan-400"> CodeHunter_</code>
					</Link>
				</h1>

				<hr className="w-3/4 my-10 opacity-50 flex z-0" />

				<div className="popluar-articles text-center">
					<h2 className="text-3xl my-4 mb-4">Popular Blogs</h2>
					<div className={styles.grid}>
						{blogs.map((e) => {
							console.log(e);
							if (e.content.length > 95)
								e.content = e.content.substring(0, 95) + `...`;
							return (
								<div className={styles.card}>
									<Link href={e.url}>
										<div>
											<h2 className="text-xl font-semibold"> {e.title} </h2>
											<p> {e.content}</p>
										</div>
									</Link>
								</div>
							);
						})}
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</>
	);
}
